### ISSUE TITLE
'IDBObjectStore': The transaction has finished.

### ISSUE THREAD

**Issue by Lunatic83** [bramski/angular-indexedDB#12]
Hi bramski,
I'm opening another issue, because I tryed to develope another way to solve the issue #11, using Restangular, I would fetch my api entity if is not stored inside indexedDB store.

$indexedDB.openStore(entityName, function(table) {
    var d = $q.defer();
    var promise = d.promise;

```
table.find(id).then(function(success) { //Change if id is used with index
    return d.resolve(success);
}, function(error) {
    Restangular.one(entityName, id).get().then(function(result) {
        table.insert(result, function(result) {
            console.log('insert ok');
        });
    });
    return d.reject(error);
});

return promise;
```

}, 'readwrite');

I have  Error: Failed to execute 'add' on 'IDBObjectStore': The transaction has finished.

I understand the reason for async callback for restangular refers to table after the transaction is closed, is there any way to keep the transaction open and manage it inside restangular callback?

Thanks a lot for your support.

G

**Comment by lucd** [comment]
Huhz
