### ISSUE TITLE
How to page?

### ISSUE THREAD

**Issue by capitanfuturo** [bramski/angular-indexedDB#14]
Hi bramski,
Thanks for your work. I'm new to angularjs and I'm trying to use this useful library in my project. My question is: I know indexeddb use cursor. Can I use it to implement a pagination function with angular-indexedDB library. I didn't found a function to access the cursor.

Best regards
Giuseppe

**Comment by bramski** [comment]
Closing this.  Feel free to re open if your question isn't addressed.
