### ISSUE TITLE
Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.

### ISSUE THREAD

**Issue by atulpatil2741** [bramski/angular-indexedDB#27]
When I am online, it's works pretty well. But when the connection get lost and perform any operation I get the above mentioned error I am not able to figure it out how to fix it.

**Comment by bramski** [comment]
I have seen this before, but I have no idea how to reproduce it.  This is an error from the underlying API; so there's not much this library can do about it. How is this happening for you?

**Comment by bramski** [comment]
April 30th to June 7th.  No repro.  Closing this issue.
