### ISSUE TITLE
Error: Failed to execute 'add' on 'IDBObjectStore': The object store uses out-of-line keys and has no key generator and the key parameter was not provided.

### ISSUE THREAD

**Issue by arnoldjair** [bramski/angular-indexedDB#37]
app.js
var cursosStore = db.createObjectStore('Cursos',
                                {keypath: 'id', autoincrement: true}
                        );

Controller
$indexedDB.openStore('materias', function (store) {
                                var materia1 = {
                                    id: 1,
                                    nombre: "prueba",
                                    descripcion: "prueba"
                                };
                                store.insert()
                                        .then(
                                                function (data) {
                                                    console.log(data);
                                                },
                                                function (error) {
                                                    console.log(error);
                                                }
                                        );
                            });

**Comment by bramski** [comment]
![tommy_kidding](https://cloud.githubusercontent.com/assets/421781/8022434/f3279fa4-0c85-11e5-9f19-0de8b0192a8e.jpg)

**Comment by bramski** [comment]
Read the docs.  Debug your issue.  Please don't waste my time.  Use github markup, write code I can reproduce or at least read.

**Comment by arnoldjair** [comment]
That is what i'm doing. But i can't find the problem. Sorry-.
