### ISSUE TITLE
angular-1.4 compatibility?

### ISSUE THREAD

**Issue by plaes** [bramski/angular-indexedDB#40]
Currently `bower.json` restricts angular version to `1.2-1.3`, but it seems to be also working with 1.4 (I have done only minimal testing: set up store, and do an upsert and query data).

Angular migration docs from 1.3-1.4: https://docs.angularjs.org/guide/migration#migrating-from-1-3-to-1-4

**Comment by pbruining** [comment]
We are also using it with AngularJS 1.4 and it seems to work fine.

**Comment by bramski** [comment]
I'm sure it's fine.  I'm slammed with other things right now.  If somebody
makes a PR for the bower changes I'll merge it and cut a releasr.
