### ISSUE TITLE
Could you please provide some usage examples ?

### ISSUE THREAD

**Issue by Yeh-Jack** [bramski/angular-indexedDB#44]
Usage examples are helpful for figure out how to use this library.

Especially, I like to know how to get the database object for binding onerror event for error handling globally like :
```
db.onerror = function(event) {
  // Generic error handler for all errors targeted at this database's
  // requests!
  alert("Database error: " + event.target.errorCode);
};
```

Thank you very much.

**Comment by bramski** [comment]
It's promise based.  All errors come from $q error callbacks.

**Comment by bramski** [comment]
Another person has added some additional useage documentation.
