### ISSUE TITLE
Throw all IndexedDB errors as promises

### ISSUE THREAD

**Issue by JamesMessinger** [bramski/angular-indexedDB#5]
Any code that interacts directly with the IndexedDB API needs to be wrapped in a `try...catch` block so that any errors can be passed to `promise.reject()` rather than being thrown up the stack.  Currently, I have to have **two** types of error handling logic in my code, because some errors are thrown **synchronously**, and others are "thrown" **asynchronously** via `promise.reject()`.   Here's an example:

``` javascript
var user = { id: 1, username: 'jdoe', password: 'password' };

$indexedDB.openStore('users', function(userStore) {
    try {
        userStore.upsert(user).then(
            function(result) {
                // Yay!  The IDBRequest.onsuccess event fired!
            },
            function(err) {
                // Onoes!  The IDBRequest.onerror event fired!
            }
        );
    }
    catch (e) {
        // Onoes!  IDBObjectStore.put threw an error!
    }
});
```

Ideally, I could get rid of the `try...catch` block entirely and just write the following code instead:

``` javascript
var user = { id: 1, username: 'jdoe', password: 'password' };

$indexedDB.openStore('users', function(userStore) {
    userStore.upsert(user).then(
        function(result) {
            // Yay!  The IDBRequest.onsuccess event fired!
        },
        function(err) {
            // Onoes!  An error occurred!  Doesn't matter whether it was IDBRequest.onerror or IDBObjectStore.put
        }
    );
});
```

**Comment by smks** [comment]
Hey Bram, could you help with this? http://stackoverflow.com/questions/36869596/angularjs-return-object-of-methods-after-indexeddb-call
