### ISSUE TITLE
Small Documentation Mistake?

### ISSUE THREAD

**Issue by corwin-of-amber** [bramski/angular-indexedDB#52]
When installing via bower, as suggested: `bower install angular-indexed-db`, I get the files placed in `bower_components/angular-indexedDB`. Seems like the `<script>` tag should be
```html
<script src="bower_components/angular-indexedDB/angular-indexed-db.js"></script>
```
then, no?

**Comment by bramski** [comment]
Sure.  You can also totally configure bower to put the files wherever you like.  But that's the default.  Please make a PR with the documentation update and I'll merge it.

**Comment by corwin-of-amber** [comment]
Yeah, the problem is not so much the name of the bower subdirectory but seems like the component name was misspelled (`angular-indexed-db` instead of `angular-indexedDB`). It's confusing since the argument to `bower install` is the former, but the directory it creates is the latter...

**Comment by bramski** [comment]
Great. Thanks for noticing.
