### ISSUE TITLE
Make package available on NPM

### ISSUE THREAD

**Issue by bendobos** [bramski/angular-indexedDB#56]
This would be really nice.

**Comment by bramski** [comment]
Sure!  Issue a PR for any needed changes and I'll put it up.

**Comment by scotttrinh** [comment]
@bramski I don't believe there is anything special you need to do to publish to NPM.

https://docs.npmjs.com/misc/developers

TL;DR:
`npm adduser`
`npm publish`

You might want to update the README to include NPM installation instructions before, but that's not strictly required. I'd love to see this happen, so let me know if there is anything I can do to help!

**Comment by bramski** [comment]
Somebody already published ```angular-indexed-db```. https://github.com/tuckerjt07/Angular-IndexedDb

**Comment by bramski** [comment]
I have published: https://www.npmjs.com/package/angularindexeddb

**Comment by bramski** [comment]
Closing this issue.
