### ISSUE TITLE
Adds then retrieves first time. Can't retrieve second time

### ISSUE THREAD

**Issue by seanmavley** [bramski/angular-indexedDB#60]
Kindly see this snippet in the README:
`angular.module('myModuleName')
  .controller('myControllerName', function($scope, $indexedDB) {

    $scope.objects = [];

    $indexedDB.openStore('people', function(store){

      store.insert({"ssn": "444-444-222-111","name": "John Doe", "age": 57}).then(function(e){...});

      store.getAll().then(function(people) {  
        // Update scope
        $scope.objects = people;
      });
    });
  });`

The `store.getAll()` should probably come out of that `indexedDB.openStore(....) { ... }` block.

When I tried the above snippet, the objects are added on first time, if the db doesn't exist, but subsequent ones, no retrieval happens

I did this and it works fine:
```
$indexedDB.openStore('myStop', function(store) {
            store.getAll().then(function(data) {
                // Update scope
                $scope.objects = data;
            });
        });
```

**Comment by bramski** [comment]
You have no catch.  Are you sure the first function succeeds a second
time?  You're using insert and not upsert so perhaps the insert is failing
due to a key clash but you're not seeing the transaction error.  I'm
guessing that ssn is your key property?

Try putting together a gist if that fails.

**Comment by seanmavley** [comment]
Yep, true. I'm using insert function, and without an error function. And yes, there's a key clash. However, it isn't clear from the docs, with the insert embedded in the openStore block. Might be confusing for newbies like myself when they realize insert worked, but results doesn't show the second time.

Not a bug report, but just a doc clarification

**Comment by bramski** [comment]
Feel free to make an addition to the Readme you feel would be helpful.
