### ISSUE TITLE
logs in code

### ISSUE THREAD

**Issue by frlinw** [bramski/angular-indexedDB#64]
Hi,

In he original code, console.logs were used for dev purpose. It seems that we can't disable them now.

**Comment by bramski** [comment]
Okay.  Do you want to configure their removal or just remove them and
submit a PR?

**Comment by frlinw** [comment]
Just remove them, i will submit a PR if you agree with that.

One question about these logs :
![indexeddb](https://cloud.githubusercontent.com/assets/11896237/15210862/8134d924-1838-11e6-9200-03e543415bf7.jpg)
I can insert data in indexeddb before upgrade process end ? 
Upgrade event is fired just after the database connection in .config, I don't understand why i see logs about upgrade during controller execution... I missed something (async thing ? how to be sure that upgrade is done before manipulate data ?)

**Comment by ankurk91** [comment]
Angular allows to disable logging.

```
app. config([ '$logProvider' , function($logProvider) {
6
$logProvider. debugEnabled(false );
7
}]);

```

https://docs.angularjs.org/api/ng/provider/$logProvider
