### ISSUE TITLE
Unnecessary runtime bower dependency

### ISSUE THREAD

**Issue by schmod** [bramski/angular-indexedDB#67]
Is it necessary to install bower as part of the preinstall and postinstall NPM scripts?

``` js
    "preinstall": "bower >/dev/null || sudo npm install bower grunt-cli -g",
    "postinstall": "bower install"
```

Eliminating these would eliminate an unnecesary installation step (and invocation of `sudo`) for NPM users.

**Comment by bramski** [comment]
Sure.  Would you like to make a PR?
